node {
  try{
    def ANDROID_HOME='/opt/android-sdk-linux'
    def ADB="$ANDROID_HOME/platform-tools/adb"

    stage('Stage Checkout') {
      git branch: 'develop', credentialsId: 'd9f13c8b', url: 'http://git.hostname.com/adfasd.git'
    }

    stage('Stage Build') {
      sh "./gradlew clean assembleRelease"
    }

    stage('Stage Unit Tests') {
      sh "./gradlew testReleaseUnitTest"
    }

    stage('Stage Instumental Tests') {
      sh "$ADB start-server"

      def error
      parallel (
        launchEmulator: {
            sh "$ANDROID_HOME/tools/qemu/linux-x86_64/qemu-system-x86_64 -engine classic -prop persist.sys.language=en -prop persist.sys.country=US -avd test -no-snapshot-load -no-snapshot-save -no-window"
        },
        runAndroidTests: {
            timeout(time: 20, unit: 'SECONDS') {
              sh "$ADB wait-for-device"
            }
            try {
                sh "./gradlew :MyKet:connectedAndroidTest"
            } catch(e) {
                error = e
            }
            sh script: '/var/lib/jenkins/kill-emu.sh'
        }
      )
      if (error != null) {
          throw error
      }
    }
    currentBuild.result = "SUCCESS"
  } catch (e) {
    currentBuild.result = "FAILED"
//    notifyFailed()
    throw e
  } finally {
    stage('Stage Clean') {
       sh script: '/var/lib/jenkins/clean.sh'
    }
  }
}



//////////////////////////////////////////////////////////////////////////////////////////////////////////
//
//
//////////////////////////////////////////////////////////////////////////////////////////////////////////
pipeline {
    agent any

    stages {
        // this is going to be the template for all the other applications that are
        // based on this framework
        stage("Checkout") {
            steps {
                echo 'checking out the source code from repository'
                git branch: 'master', credentialsId: '605875c4-f104-41e1-8fc2-729e60aa0711', url: 'git@github.com:adamszewe/android-apc.git'
            }
        }


        stage("Build") {
            steps {
                echo 'building...'
                sh './gradlew clean assembleRelease'
            }
        }

        stage("Unit Testing") {
            steps {
                echo 'testing'
                sh './gradlew :app:testFlavor00_DevelopmentReleaseUnitTest'
            }
        }


        stage("Quality Assurance - Code Quality Testing") {
            steps {

            }
        }


        stage("UI Testing") {
            steps {
                // test on local emulators
                // test on remote devices


            }
        }



        stage("Delivery") {
            steps {
                // delivery to s3 bucket
                //
            }
        }

    }



}


